# OGSenpai Configuration

# LLM Configuration
llm:
  model: deepseek-coder-33b-instruct
  temperature: 0.7
  maxTokens: 2048

# Memory Configuration
memory:
  maxSize: 1000  # Maximum number of memories to store
  ttl: 3600000   # Time to live in milliseconds (1 hour)

# Consciousness Configuration
consciousness:
  attentionThreshold: 0.5  # Minimum attention level for processing
  awarenessInterval: 1000  # Awareness update interval in milliseconds

# Knowledge Base Configuration
knowledge:
  basePath: knowledge-base
  categories:
    - core       # Core principles and concepts
    - skills     # Practical skills and techniques
    - wisdom     # Philosophical insights and teachings
    - practices  # Training methods and exercises

# Logging Configuration
logging:
  level: info
  file:
    enabled: true
    path: logs
    maxSize: 5242880  # 5MB
    maxFiles: 5 