version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs
    depends_on:
      - supabase-db
      - supabase

  supabase:
    image: supabase/supabase-dev
    ports:
      - "54321:54321"
      - "54322:54322"
    environment:
      POSTGRES_PASSWORD: your-super-secret-password
      JWT_SECRET: your-super-secret-jwt-token
      DASHBOARD_USERNAME: admin
      DASHBOARD_PASSWORD: admin
    depends_on:
      - supabase-db

  supabase-db:
    image: supabase/postgres
    ports:
      - "54323:5432"
    environment:
      POSTGRES_PASSWORD: your-super-secret-password
    volumes:
      - ./supabase/init:/docker-entrypoint-initdb.d
      - supabase-db-data:/var/lib/postgresql/data

  supabase-studio:
    image: supabase/studio
    ports:
      - "54324:3000"
    environment:
      SUPABASE_URL: http://localhost:54321
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs
    depends_on:
      - supabase

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  supabase-db-data:
  redis-data: 